### ISSUE TITLE
Push newest version to crates.io

### ISSUE THREAD

**Issue by umgefahren** [iqlusioninc/keychain-services-rs#26]
The version currently published on [crates.io](https://crates.io/crates/keychain-services) depends on zeroize 0.4 which is a yanked release. The version in this repository however specifies the use of zeroize 1.1 in Cargo.toml. Please consider to upload the newest version to crates.io in order to make the crate usable again.

**Comment by GeorgiiFirsov** [comment]
Temporary solution is to specify the dependency as follows:
```toml
[dependencies]
keychain-services = { git = "https://github.com/iqlusioninc/keychain-services.rs" }
```
